# file: postgresql/tasks/extensions/postgis.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}.yml"
    - "../vars/empty.yml"

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Debian or Ubuntu
  apt:
    name: "{{ postgresql_ext_postgis_deps_debian }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | Fedora
  dnf:
    name: "postgis{{ posgresql_postgis_version }}"
    state: present
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Fedora"
  notify:
    - restart postgresql

- block:
  - name: PostgreSQL | Install repo pgdg | CentOS 7 | yum
    yum:
      name: "{{ postgresql_pgdg_repository_url }}/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
      state: present
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | RedHat 7 or CentOS 7
    shell: yum install -y postgis{{ postgresql_postgis_version }} --nobest
    args:
      warn: false
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    notify:
      - restart postgresql

- block:
  - name: PostgreSQL | Install repo pgdg | CentOS 8 | dnf
    dnf:
      name: "{{ postgresql_pgdg_repository_url }}/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
      state: present
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

  - name: PostgreSQL | Check if CentOS 8 PowerTools repo enabled
    shell: dnf -y config-manager --set-enabled PowerTools
    args:
      warn: no
    register: check_repo
    failed_when: check_repo.rc == "0"
    changed_when: false
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

  - name: PostgreSQL | Fix | Check if CentOS 8 powertools repo enabled
    shell: dnf -y config-manager --set-enabled powertools
    args:
      warn: no
    register: check_repo
    failed_when: check_repo.rc == "0"
    changed_when: false
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

  - name: PostgreSQL | Extensions | Make sure the postgis extensions are installed | RedHat 8 or CentOS 8
    shell: dnf install -y postgis{{ postgresql_postgis_version }} --nobest
    args:
      warn: false
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    notify:
      - restart postgresql
