# file: postgresql/tasks/install_dnf.yml

# The standard ca-certs are needed because  without them dnf will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgrSQL | Install all the required dependencies | dnf
        dnf:
          name: "ca-certificates, python*-pycurl, glibc-common, libselinux-python*, python*-psycopg2"
          state: present

      - name: PostgreSQL | Add yum Repository | Fedora | dnf
        yum_repository:
          name: postgresql
          state: present
          description: postgresql yum repo
          baseurl: "{{ postgresql_dnf_repository_baseurl }}"
          gpgkey: "{{ postgresql_dnf_repository_gpgkey }}"
        when: postgresql_install_repository and ansible_distribution == "Fedora"

      - name: PostgreSQL | Add yum Repository | CentOS | dnf
        yum_repository:
          name: postgresql
          state: present
          description: postgresql yum repo
          baseurl: "{{ postgresql_yum_repository_baseurl }}"
          gpgkey: "{{ postgresql_yum_repository_gpgkey }}"
        when: postgresql_install_repository and ansible_distribution == "CentOS"

      - name: PostgreSQL | Disable Postgresql module on CentOS | dnf
        command: dnf module disable postgresql -y
        args:
          warn: no
        when: postgresql_install_repository and ansible_distribution == "CentOS"

      - name: PostgreSQL | Install PostgreSQL | dnf
        dnf:
          name: "postgresql{{ postgresql_version_terse }}-server,postgresql{{ postgresql_version_terse }},postgresql{{ postgresql_version_terse }}-contrib"
          state: present
        environment: "{{ postgresql_env }}"

      - name: PostgreSQL | PGTune | dnf
        dnf:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune

  - block:
      - name: Check if pgpool service exists
        command: systemctl cat pgpool
        check_mode: no
        register: pgpool_exists
        changed_when: False
        failed_when: pgpool_exists.rc not in [0, 1]

      - name: Stop service pgpool
        systemd:
          name: pgpool
          state: stopped
          enabled: no
        when: pgpool_exists.rc == 0

